name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main # Triggers when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project kairos-e3e51
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

